# Autogenerated wrapper script for OSRM_jll for armv6l-linux-musleabihf-cxx11
export bicycle_lua, car_lua, foot_lua, lib_access_lua, lib_destination_lua, lib_guidance_lua, lib_maxspeed_lua, lib_measure_lua, lib_pprint_lua, lib_profile_debugger_lua, lib_relations_lua, lib_sequence_lua, lib_set_lua, lib_tags_lua, lib_traffic_signal_lua, lib_utils_lua, lib_way_handlers_lua, libosrm, osrm_components, osrm_contract, osrm_customize, osrm_datastore, osrm_extract, osrm_partition, osrm_routed

using boost_jll
using Lua_jll
using oneTBB_jll
using Expat_jll
using XML2_jll
using libzip_jll
using Bzip2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("OSRM")
JLLWrappers.@declare_file_product(bicycle_lua)
JLLWrappers.@declare_file_product(car_lua)
JLLWrappers.@declare_file_product(foot_lua)
JLLWrappers.@declare_file_product(lib_access_lua)
JLLWrappers.@declare_file_product(lib_destination_lua)
JLLWrappers.@declare_file_product(lib_guidance_lua)
JLLWrappers.@declare_file_product(lib_maxspeed_lua)
JLLWrappers.@declare_file_product(lib_measure_lua)
JLLWrappers.@declare_file_product(lib_pprint_lua)
JLLWrappers.@declare_file_product(lib_profile_debugger_lua)
JLLWrappers.@declare_file_product(lib_relations_lua)
JLLWrappers.@declare_file_product(lib_sequence_lua)
JLLWrappers.@declare_file_product(lib_set_lua)
JLLWrappers.@declare_file_product(lib_tags_lua)
JLLWrappers.@declare_file_product(lib_traffic_signal_lua)
JLLWrappers.@declare_file_product(lib_utils_lua)
JLLWrappers.@declare_file_product(lib_way_handlers_lua)
JLLWrappers.@declare_library_product(libosrm, "libosrm.so")
JLLWrappers.@declare_executable_product(osrm_components)
JLLWrappers.@declare_executable_product(osrm_contract)
JLLWrappers.@declare_executable_product(osrm_customize)
JLLWrappers.@declare_executable_product(osrm_datastore)
JLLWrappers.@declare_executable_product(osrm_extract)
JLLWrappers.@declare_executable_product(osrm_partition)
JLLWrappers.@declare_executable_product(osrm_routed)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, Lua_jll, oneTBB_jll, Expat_jll, XML2_jll, libzip_jll, Bzip2_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        bicycle_lua,
        "profiles/bicycle.lua",
    )

    JLLWrappers.@init_file_product(
        car_lua,
        "profiles/car.lua",
    )

    JLLWrappers.@init_file_product(
        foot_lua,
        "profiles/foot.lua",
    )

    JLLWrappers.@init_file_product(
        lib_access_lua,
        "profiles/lib/access.lua",
    )

    JLLWrappers.@init_file_product(
        lib_destination_lua,
        "profiles/lib/destination.lua",
    )

    JLLWrappers.@init_file_product(
        lib_guidance_lua,
        "profiles/lib/guidance.lua",
    )

    JLLWrappers.@init_file_product(
        lib_maxspeed_lua,
        "profiles/lib/maxspeed.lua",
    )

    JLLWrappers.@init_file_product(
        lib_measure_lua,
        "profiles/lib/measure.lua",
    )

    JLLWrappers.@init_file_product(
        lib_pprint_lua,
        "profiles/lib/pprint.lua",
    )

    JLLWrappers.@init_file_product(
        lib_profile_debugger_lua,
        "profiles/lib/profile_debugger.lua",
    )

    JLLWrappers.@init_file_product(
        lib_relations_lua,
        "profiles/lib/relations.lua",
    )

    JLLWrappers.@init_file_product(
        lib_sequence_lua,
        "profiles/lib/sequence.lua",
    )

    JLLWrappers.@init_file_product(
        lib_set_lua,
        "profiles/lib/set.lua",
    )

    JLLWrappers.@init_file_product(
        lib_tags_lua,
        "profiles/lib/tags.lua",
    )

    JLLWrappers.@init_file_product(
        lib_traffic_signal_lua,
        "profiles/lib/traffic_signal.lua",
    )

    JLLWrappers.@init_file_product(
        lib_utils_lua,
        "profiles/lib/utils.lua",
    )

    JLLWrappers.@init_file_product(
        lib_way_handlers_lua,
        "profiles/lib/way_handlers.lua",
    )

    JLLWrappers.@init_library_product(
        libosrm,
        "lib/libosrm.so",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        osrm_components,
        "bin/osrm-components",
    )

    JLLWrappers.@init_executable_product(
        osrm_contract,
        "bin/osrm-contract",
    )

    JLLWrappers.@init_executable_product(
        osrm_customize,
        "bin/osrm-customize",
    )

    JLLWrappers.@init_executable_product(
        osrm_datastore,
        "bin/osrm-datastore",
    )

    JLLWrappers.@init_executable_product(
        osrm_extract,
        "bin/osrm-extract",
    )

    JLLWrappers.@init_executable_product(
        osrm_partition,
        "bin/osrm-partition",
    )

    JLLWrappers.@init_executable_product(
        osrm_routed,
        "bin/osrm-routed",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
